// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBItK1FIypR1ZuGwtyITvSspR2ZBirjkNE',
    appId: '1:167895460051:web:d8f5f7bb903ba3cc470c26',
    messagingSenderId: '167895460051',
    projectId: 'notificaciones-athlos-s-a',
    authDomain: 'notificaciones-athlos-s-a.firebaseapp.com',
    storageBucket: 'notificaciones-athlos-s-a.firebasestorage.app',
    measurementId: 'G-895GBXDDQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnOX-BVUK9GLG4IsXUWENZFN52buI59NU',
    appId: '1:167895460051:android:6dc08fb9d793b732470c26',
    messagingSenderId: '167895460051',
    projectId: 'notificaciones-athlos-s-a',
    storageBucket: 'notificaciones-athlos-s-a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4-yb_xoDAQIyE6Q4Z98Bup0bCO-V4XA4',
    appId: '1:167895460051:ios:866e75b2c8d94416470c26',
    messagingSenderId: '167895460051',
    projectId: 'notificaciones-athlos-s-a',
    storageBucket: 'notificaciones-athlos-s-a.firebasestorage.app',
    iosBundleId: 'com.example.workspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4-yb_xoDAQIyE6Q4Z98Bup0bCO-V4XA4',
    appId: '1:167895460051:ios:866e75b2c8d94416470c26',
    messagingSenderId: '167895460051',
    projectId: 'notificaciones-athlos-s-a',
    storageBucket: 'notificaciones-athlos-s-a.firebasestorage.app',
    iosBundleId: 'com.example.workspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBItK1FIypR1ZuGwtyITvSspR2ZBirjkNE',
    appId: '1:167895460051:web:7d4d6f6df632b049470c26',
    messagingSenderId: '167895460051',
    projectId: 'notificaciones-athlos-s-a',
    authDomain: 'notificaciones-athlos-s-a.firebaseapp.com',
    storageBucket: 'notificaciones-athlos-s-a.firebasestorage.app',
    measurementId: 'G-W89QYM7N50',
  );
}
